# name of the software
name: Minio Docs
# current version of the software
version: 1.1.0
# url of the download button
downloadUrl: https://github.com/minio/docs
 
# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url:  https://github.com/minio/docs

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url:  https://github.com/minio/docs
  - title: Issues
    url:  https://github.com/minio/docs
# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: minio
  repo: docs

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile', 'gulpfile.js', 'node_modules', 'package.json', 'less']

markdown: rdiscount

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

# SDK
sdk:
  - title: Golang
    class: golang
  - title: Node.js
    class: nodejs
  - title: Python
    class: python
  - title: Java
    class: java

#documentation links
docLinks:
  - title : Minio Server
    url   : minio-server
  - title : Minio Client
    url   : minio-client
  - title : Minio SDK
    url   : minio-sdk
  - title : Minio SDK Golang
    url   : minio-golang
  - title : Minio SDK Node.js
    url   : minio-nodejs
  - title : Minio SDK Python
    url   : minio-python
  - title : Minio SDK Java
    url   : minio-java

# inner links [more to come: Recipies & Best Practices]
innerLinks:
  - title     : Quick Start Guide
    urlPrefix :

# minio server, client & description
minioDownload:
  - title      : <span>GNU/Linux</span> x64
    downloadms : https://dl.minio.io/server/minio/release/linux-amd64/minio
    downloadmc : https://dl.minio.io/client/mc/release/linux-amd64/mc
    icon       : linux
  - title      : <span>GNU/Linux</span> x32
    downloadms : https://dl.minio.io/server/minio/release/linux-386/minio
    downloadmc : https://dl.minio.io/client/mc/release/linux-386/mc
    icon       : linux
  - title      : <span>GNU/Linux</span> A32
    downloadms : https://dl.minio.io/server/minio/release/linux-arm/minio
    downloadmc : https://dl.minio.io/client/mc/release/linux-arm/mc
    icon       : linux
  - title      : <span>Mac OSX</span> x64
    downloadms : https://dl.minio.io/server/minio/release/darwin-amd64/minio
    downloadmc : https://dl.minio.io/client/mc/release/darwin-amd64/mc
    icon       : apple
  - title      : <span>Windows</span> x64
    downloadms : https://dl.minio.io/server/minio/release/windows-amd64/minio.exe
    downloadmc : https://dl.minio.io/client/mc/release/windows-amd64/mc.exe
    icon       : windows
  - title      : <span>Windows</span> x32
    downloadms : https://dl.minio.io/server/minio/release/windows-386/minio.exe
    downloadmc : https://dl.minio.io/client/mc/release/windows-386/mc.exe
    icon       : windows
  - title      : <span>Solaris</span> x64
    downloadms :
    downloadmc : https://dl.minio.io/client/mc/release/solaris-amd64/mc
    icon       : cube
  - title      : <span>FreeBSD</span> x64
    downloadms :
    downloadmc : https://dl.minio.io/client/mc/release/freebsd-amd64/mc
    icon       : cube

minioGuide:
  - title    : GNU/Linux
    tab      : linux-amd64
    icon     : linux
    order    : 1
  - title    : Mac OSX
    tab      : darwin-amd64
    icon     : apple
    order    : 2
  - title    : Windows
    tab      : windows-amd64
    icon     : windows
    order    : 3
  - title    : Docker
    tab      : docker
    icon     : cube
    order    : 7
  - title    : Source
    tab      : source
    icon     : cube
    order    : 6
  - title    : Solaris
    tab      : solaris-amd64
    icon     : cube
    order    : 4
  - title    : FreeBSD
    tab      : freebsd-amd64
    icon     : cube
    order    : 5

msInstallInfo: '<ol class="list-alt">
                    <li>Start the Minio Server on any folder and you should see the AccessKey and SecretKey printed as shown below.</li>
                    <li>Your end point for object storage is shown below.</li>
                    <li>You may also access the Minio Browser in your web browser at the same URLs. Use your AccessKey and SecretKey to login.</li>
                </ol>'